routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::resource('countries', 'CountriesController');
Route::resource('citiesbycountries', 'CitiesbyCountriesController');
Route::resource('colors', 'ColorsController');
Route::resource('moneys', 'MoneysController');
Route::resource('categories', 'CategoriesController');
Route::resource('subcategories', 'SubCategoriesController');
Route::resource('alloys', 'AlloysController');
Route::resource('colors', 'ColorsController');
Route::resource('moneys', 'MoneysController');
Route::resource('status', 'StatusController');
Route::resource('unittypes', 'UnitTypesController');
Route::resource('reviews', 'ReviewsController');
Route::resource('rolls', 'RollsController');
Route::resource('presentations', 'PresentationsController');
Route::resource('wharehouse', 'WhareHouseController');
Route::resource('companies', 'CompaniesController');
Route::resource('providers', 'ProvidersController');
Route::resource('assemblies', 'AssembliesController');
Route::resource('movementstypes', 'MovementstypesController');
Route::resource('managersbyproviders', 'ManagersbyProvidersController');
Route::resource('locationbywharehouses', 'LocationbyWharehousesController');
Route::resource('masterproducts', 'MasterProductsController');
Route::resource('sections', 'SectionsController');
Route::resource('purchaseorder', 'PurchaseOrderController');



Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/countries', 'HomeController@indexCountries')->name('countries');
//Route::get('/citiesbycountries', 'HomeController@indexCitiesbycountries')->name('citiesbycountries');


Route::post('countries/action', 'CountriesController@action')->name('countries.action');
Route::post('countries-research', 'CountriesController@countries_research')->name('countries_research');
Route::get('findcountry', 'CountriesController@findcountry')->name('findcountry');

Route::get('citiesbycountries', 'CitiesbyCountriesController@index')->name('citiesbycountries');
Route::post('citiesbycountries_research', 'CitiesbyCountriesController@citiesbycountries_research')->name('citiesbycountries_research');
Route::post('citiesbycountries_action', 'CitiesbyCountriesController@action')->name('citiesbycountries.action');

Route::post('categories_research', 'CategoriesController@categories_research')->name('categories_research');
Route::post('categories_action', 'CategoriesController@action')->name('categories.action');

Route::post('subcategories_research', 'SubCategoriesController@subcategories_research')->name('subcategories_research');
Route::post('subcategories_action', 'SubCategoriesController@action')->name('subcategories.action');

Route::post('alloys_research', 'AlloysController@alloys_research')->name('alloys_research');
Route::post('alloys_action', 'AlloysController@action')->name('alloys.action');

Route::post('colors_research', 'ColorsController@colors_research')->name('colors_research');
Route::post('colors_action', 'ColorsController@action')->name('colors.action');

Route::post('moneys_research', 'MoneysController@moneys_research')->name('moneys_research');
Route::post('moneys_action', 'MoneysController@action')->name('moneys.action');

Route::post('status_research', 'StatusController@status_research')->name('status_research');
Route::post('status_action', 'StatusController@action')->name('status.action');

Route::post('unittypes_research', 'UnitTypesController@unittypes_research')->name('unittypes_research');
Route::post('unittypes_action', 'UnitTypesController@action')->name('unittypes.action');

Route::post('reviews_research', 'ReviewsController@reviews_research')->name('reviews_research');
Route::post('reviews_action', 'ReviewsController@action')->name('reviews.action');

Route::post('rolls_research', 'RollsController@rolls_research')->name('rolls_research');
Route::post('rolls_action', 'RollsController@action')->name('rolls.action');

Route::post('presentations_research', 'PresentationsController@presentations_research')->name('presentations_research');
Route::post('presentations_action', 'PresentationsController@action')->name('presentations.action');

Route::post('wharehouse_research', 'WhareHouseController@research')->name('wharehouse_research');
Route::post('wharehouse_action', 'WhareHouseController@action')->name('wharehouse.action');

Route::post('companies_research', 'CompaniesController@research')->name('companies_research');
Route::post('companies_action', 'CompaniesController@action')->name('companies.action');
Route::post('companies_citiesbycountries', 'CompaniesController@citiesbycountries')->name('companies_citiesbycountries');

Route::post('providers_research', 'ProvidersController@research')->name('providers_research');
Route::post('providers_action', 'ProvidersController@action')->name('providers.action');
Route::post('providers_citiesbycountries', 'ProvidersController@findcitiesbycountries')->name('providers_citiesbycountries');

Route::post('movementstypes_research', 'MovementstypesController@research')->name('movementstypes_research');
Route::post('movementstypes_action', 'MovementstypesController@action')->name('movementstypes.action');
Route::post('movementstypes_exist', 'MovementstypesController@movementstypes_exist')->name('movementstypes_exist');

Route::post('managersbyproviders_research', 'ManagersbyProvidersController@research')->name('managersbyproviders_research');
Route::post('managersbyproviders_action', 'ManagersbyProvidersController@action')->name('managersbyproviders.action');
Route::post('wharehousebycompany', 'ManagersbyProvidersController@wharehousebycompany')->name('wharehousebycompany');

Route::post('locationbywharehouses_research', 'LocationbyWharehousesController@research')->name('locationbywharehouses_research');
Route::post('locationbywharehouses_action', 'LocationbyWharehousesController@action')->name('locationbywharehouses.action');
//Route::post('wharehousebycompany', 'LocationbyWharehousesController@wharehousebycompany')->name('wharehousebycompany');

Route::post('masterproducts_research', 'MasterProductsController@research')->name('masterproducts_research');
Route::post('masterproducts_action', 'MasterProductsController@action')->name('masterproducts.action');
Route::post('masterproducts_search', 'MasterProductsController@products_search')->name('masterproducts_search');
Route::post('masterproducts_subcategories', 'MasterProductsController@subcategories')->name('masterproducts_subcategories');
Route::post('masterproducts_locations', 'MasterProductsController@locations')->name('masterproducts_locations');
Route::post('masterproducts_sections', 'MasterProductsController@sections')->name('masterproducts_sections');
Route::post('masterproducts_action', 'MasterProductsController@action')->name('masterproducts.action');

Route::post('sections_research', 'SectionsController@research')->name('sections_research');
Route::post('sections_action', 'SectionsController@action')->name('sections.action');
Route::post('sections_locationsbywharehousesandcompany', 'SectionsController@locationsbywharehouseandcompany')->name('sections_locationsbywharehousesandcompany');

Route::post('assemblies_research', 'AssembliesController@research')->name('assemblies_research');
Route::post('assemblies_action', 'AssembliesController@action')->name('assemblies.action');

Route::post('purcharseorderproducts', 'PurchaseOrderController@searchProducts')->name('purcharseorderproducts');
Route::post('purcharseorderproviders', 'PurchaseOrderController@searchProviders')->name('purcharseorderproviders');
Route::post('purcharseorder_action', 'PurchaseOrderController@action')->name('purcharseorder.action');
Route::post('purcharseorder_actiondetails', 'PurchaseOrderController@actiondetails')->name('purcharseorder.actiondetails');

resources/views/assemblies/create.blade.php
@extends('layouts.app')

@section('content')
<div id="content">

    @include('layouts.navbar')

    <div class="container-fluid p-md-4">  

        <div class="content-wrapper">

            <section class="content-header card-header">
                <h1><i class="fa fa-edit"></i>Create Assemblies</h1>
            </section>

            <section class="content">
                <div class="box">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-12">
                            
                                <form id="form-assemblies" method="POST" action="" class="needs-validation" novalidate>
                                    
                                    <input name="_token" type="hidden"  value="{{ csrf_token() }}">

                                    <div class="col-md-12">
                                        <div class="row ">                                           

                                            <div class="col-md-2">
                                                <div class="form-group">
                                                <label for="inputAssembliesCode" class="col-2 col-form-label">Code</label>
                                                    <div class="">
                                                        <input type="text" class="form-control uppder" id="inputAssembliesCode" placeholder="Code" maxlength="30" required>
                                                        <div class="invalid-feedback">Please fill out this field.</div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-3">
                                                <div class="form-group">
                                                <label for="inputAssembliesName" class="col-2 col-form-label">Name</label>
                                                    <div class="">
                                                        <input type="text" class="form-control uppder" id="inputAssembliesName" placeholder="Name" maxlength="50" required>
                                                        <div class="invalid-feedback">Please fill out this field.</div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-2">
                                                <div class="form-group">
                                                <label for="selectAssembliesReview" class="col-2 col-form-label">Review</label>
                                                    <div class="col-10">
                                                        <select id="selectAssembliesReview" class="form-control input-sm" required>
                                                            <option hidden value="-1">Reviews</option> 
                                                            
                                                        </select>
                                                        <div class="invalid-feedback">Please fill out this field.</div>
                                                    </div>
                                                </div>
                                            </div> 

                                            <div class="col-md-2">
                                                <div class="form-group">
                                                <label for="selectAssembliesColor" class="col-2 col-form-label">Color</label>
                                                    <div class="col-10">
                                                        <select id="selectAssembliesColor" class="form-control input-sm" required>
                                                            <option hidden value="-1">Colors</option> 
                                                            
                                                        </select>
                                                        <div class="invalid-feedback">Please fill out this field.</div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <img src="" class="ml-3" id="previewImg" width="100%" height="100%">  
                                                </div>
                                            </div>                                   

                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="row ">
                                        

                                            <div class="col-md-3">
                                                <div class="form-group">
                                                <label for="inputAssembliesCost" class="col-2 col-form-label">Cost</label>
                                                    <div class="col-10">
                                                        <input type="number" class="form-control" id="inputAssembliesCost" placeholder="Cost" required>
                                                    </div>
                                                    <div class="invalid-feedback">Please fill out this field.</div>
                                                </div>
                                            </div>

                                            <div class="col-md-3">
                                                <div class="form-group">
                                                <label for="inputAssembliesPrice" class="col-2 col-form-label">Price</label>
                                                    <div class="col-10">
                                                        <input type="number" class="form-control" id="inputAssembliesPrice" placeholder="Price" required>
                                                    </div>
                                                    <div class="invalid-feedback">Please fill out this field.</div>
                                                </div>
                                            </div>

                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label for="selectAssembliesPartType" class="col-2 col-form-label">Part</label>
                                                    <div class="col-10">
                                                        <select id="selectAssembliesPartType" class="form-control input-sm" required>
                                                            <option hidden value="-1">Part Type</option> 
                                                        </select>
                                                        <div class="invalid-feedback">Please fill out this field.</div>
                                                    </div>
                                                </div>  
                                            </div>

                                            <div class="col-md-3">
                                                <div class="form-group">
                                                    <label for="customFileLang" class="col-2 col-form-label">Image:</label>                                                                                                           
                                                    <div class="custom-file">                                                        
                                                        <input id="customFileLang" type="file" class="custom-file-input" lang="es">
                                                        <label class="custom-file-label" for="customFileLang">Select file</label>
                                                    </div>
                                                </div>
                                            </div>   
                                                                           
                                        </div>
                                    </div>

                                     <div class="col-md-12">
                                        <button id = "btn-add" type="button" class="btn btn-info btn-lg btn-block btn-send" data-toggle="tooltip" title="Add products">                                            
                                            Add
                                        </button>    
                                    </div>  
                                </form> <!--form master-products-->  
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div><!--<div class="container-fluid">-->

        

     <!--------------------Msg Modal------------------------------------------>             
     <div class="modal fade" id="modal-msg" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
              <div class="modal-header modall-he">
                      <h2 class="modal-title" id="exampleModalLabel">Inventory KW</h2>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div id="error-msg" class="modal-body">
                     {{$error_msg}}
                  </div>
                  <div class="modal-footer modall-fo">
                      <button id="btt-id-err-msg" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>                      
                  </div>
              </div>
          </div>
     </div>                   
    <!--------------------Fin Msg Modal------------------------------------------>       

</div> <!--div class="content"--> 

@endsection

@section('scripts')
    <script src="{{ asset('js/jq/assemblies_create_jq.js') }}" defer></script>
@show

resources/views/assemblies/index.blade.php
@extends('layouts.app')

@section('content')
<div id="content">

    @include('layouts.navbar')

    <div class="container-fluid p-md-4">  

        <div id="card-ppal" class="card mb-3">		        	
            <div class="card-header" id="cardd-hea">
                  <h1>Assemblies </h1>
            </div> 

            <div name= "card-body-ppal" class="card-body">
                <div name="row0-card-body-ppal" class="row">                                    
                    <div name="col1-row0-card-body-ppal" class="col-5">                      
                        <div class="form-group">
                            <form id="form-master-search" method="post" action="">
                                <input name="_token" type="hidden"  value="{{ csrf_token() }}">
                                <div class="input-group mb-3">
                                    <input  id="input_search_assemblies" class="form-control" type="search" size="30" name="find_products"  placeholder="Name / Code." />
                                    <button id="btn-search" class="btn btn-default" type="button">
                                        <span class="fa fa-search  icon"></span>
                                    </button>
                                </div>
                            </form>
                        </div>                                                
                    </div>   

                    <div name="col2-row0-card-body-ppal" class="col-5">              
                    </div>         

                    <div name="col3-row0-card-body-ppal" class="col-1">                                                                      
                        <form  method="GET" action="{{ route('assemblies.create') }}">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">       
                            <button id = "btn-add" type="submit" class="btn btn-info" data-toggle="tooltip" title="Add products">
                                    <span class="fa fa-plus" aria-hidden="true"></span>                                    
                            </button>        
                        </form>
                    </div>                                                             
                </div>
            </div> <!--card-body-->
        </div>


        
        <!-----------------------------------Mostrar datos-------------------------------------->
        <div id="card-master-products" class="card mb-3">        
            <div id="cardd-hea" class="card-header">                                    
                <h3>Assemblies</h3> 
            </div>
             
            <div id="data" class="card-body">
                <div class="row">
                    <div class="col-12">
                        <div id="div_table_assemblies" class="table-responsive">                          
                        @if(!is_null($data_result))                             
                            <table id="tableassemblies" class="table table-striped" cellspacing="0" width="100%">
                                <thead class="thead-dark">
                                    <tr>            
                                        <th>Id</th>     
                                        <th>Code</th>         
                                        <th>Name</th>
                                        <th>Description</th> 
                                        <th>Cost</th>     
                                        <th>Price</th>                                                        
                                        <th>Color</th> 
                                        <th>Review</th>                                                                                                
                                        <th>Id_Color</th>
                                        <th>Id_Review</th>                                             
                                        <th>Enabled</th>     
                                        <th>Visible</th>   
                                        <th></th>                                                                                                
                                    </tr>
                                </thead>                         
                            </table>       
                            @endif                          
                        </div>
                    </div>      
                </div> 
            </div>
        </div> 
        <!-----------------------------------Mostrar datos-------------------------------------->        
                
    </div><!--<div class="container-fluid">-->


    <!--------------------Msg Modal------------------------------------------>             
    <div class="modal fade" id="modal-msg" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header modall-he">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h2 class="modal-title" id="exampleModalLabel">Inventory KW</h2>
                </div>
                <div id="error-msg" class="modal-body">
                   {{$error_msg}}
                </div>
                <div class="modal-footer modall-fo">
                    <button id="btt-id-err-msg" type="button" class="btn btn-danger" data-dismiss="modal">Close</button>                      
                </div>
            </div>
          </div>
     </div>                   
    <!--------------------Fin Msg Modal------------------------------------------>       

</div> <!--div class="content"--> 

@endsection

@section('scripts')
    <script src="{{ asset('js/jq/assemblies_index_jq.js') }}" defer></script>
@show